# This playbook installs the tools I require for my software development
# workflow (regardles of language-specific tools).

- hosts: localhost
  connection: local

  tasks:
    - name: "Ensure utilities are installed."
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - zsh
        - bat
        - direnv
        - exa
        - fd
        - fzf
        - git
        - htop
        - jq
        - ripgrep
        - starship
        - nnn

    - name: "Ensure ~/.zshrc config is up to date."
      ansible.builtin.copy:
        src: zsh/zshrc
        dest: "{{ ansible_env.HOME }}/.zshrc"

    - name: "Get information about aliases defined in the `zshrc`."
      shell: zsh -c '. ~/.zshrc && alias'
      register: zsh_aliases_result

    - name: "Test that the aliases I like are present on the shell environment."
      assert:
        that:
          - "'g=git' in zsh_aliases_result.stdout"
          - "'ls=exa' in zsh_aliases_result.stdout"
          - "'vim=nvim' in zsh_aliases_result.stdout"
          - "'cat=bat' in zsh_aliases_result.stdout"

    - name: "Get information about ENV vars defined in the `zshrc`."
      shell: zsh -c '. ~/.zshrc && env'
      register: zsh_env_result

    - name: "Test that the ENV vars I like are set on the shell environment."
      assert:
        that:
          - "'EDITOR=nvim' in zsh_env_result.stdout"
          - "'XDG_CONFIG_HOME={{ ansible_env.HOME }}/.config' in zsh_env_result.stdout"
