#! /usr/bin/env zsh

ln -sf $(pwd)/zsh/zprezto ~/.zprezto

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -sf "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

ln -sf $(pwd)/zsh/zpreztorc ~/.zpreztorc
