#! /usr/bin/env zsh

# Declare XDG Base Directory Specification directories. These environment
# variables might not be set in some operative systems or distributions.
#
# See https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_CACHE_HOME="${HOME}/.cache"
export LOCAL_BIN="${HOME}/.local/bin"

# Tell Zsh to look for it's dotfiles at the $XDG_CONFIG_HOME. I like to keep my
# $HOME tidy.
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
